config/routes.rb
Rails.application.routes.draw do
 
  resources :answers

  resources :admin

  root 'admin#home' 

  get 'about'=>'admin#about', as: :about
 
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	
	include HasGravatar
	belongs_to :blog
	
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	
	include HasGravatar
	has_many :answer
end

app/models/concerns/has_gravatar.rb
module HasGravatar
	def gravatar
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
   
   def home
  	@blog=Blog.order(created_at: :desc).all 
  	#logger.info("+++++++++++++++++++++++++++++++++++++++++++hello from class method")
  end

  def about
  end

  def create
  	if (Blog.create(blog_params)) 
        flash[:success] = "Create question success!"
        redirect_to :root
      else
        flash[:error] = "Create question error!"
     end
  end
  def show
  	@blog = Blog.find(params[:id])
    @answer = @blog.answer.order(created_at: :desc) 

  end

  private 
  def blog_params
  	params.require(:blog).permit(:email, :body)  	
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		blog = Blog.find(params[:answer][:blog_id])
		if (blog.answer.create(answer_param) )
			flash[:success] = "Create answer success!"
			redirect_to :back
		else 
			flash[:error] = "Create answer error!"
		end
	end
	def index
		@answer = Answer.order(created_at: :desc).all
	end
	private 
	def answer_param
		params.require(:answer).permit(:blog_id, :email, :body)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale
	  Rails.application.routes.default_url_options[:locale]= I18n.locale 
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	 def blog
  end
end

app/helpers/admin_helper.rb
module AdminHelper
	def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success" # Green
      when :error
        "alert-danger" # Red
      when :alert
        "alert-warning" # Yellow
      when :notice
        "alert-info" # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/admin/_new_answer_form.html.erb
<%= form_for :@answer, method: "POST",:url => {:controller => :answers, :action => :create } do |f| %> 
    <div id="answerModal" class="modal fade" role="dialog" 
     aria-labelledby="gridSystemModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="gridSystemModal">Post answer</h4>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-3">Email: 
					<input type="hidden" value="<%=  @blog.id %>" name="answer[blog_id]"/>
              </div>
              <div class="col-md-9">
                <input type="email" name="answer[email]" class="form-control" required placeholder="Email">
              </div>
            </div>
            <div class="row">
              <div class="col-md-3">Question content :</div>
              <div class="col-md-9">
              <textarea class="form-control" name="answer[body]" rows="5" placeholder="Write question here" required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Answer</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  <% end %>

app/views/admin/_new_blog_form.html.erb
<%= form_for :@blog, method: "POST",:url => {:controller => :admin, :action => :create } do |f| %> 
    <div id="gridSystemModal" class="modal fade" role="dialog" 
     aria-labelledby="gridSystemModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="gridSystemModal">Post question</h4>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-3">Email: </div>
              <div class="col-md-9">
                <input type="email" name="blog[email]" class="form-control" required placeholder="Email">
              </div>
            </div>
            <div class="row">
              <div class="col-md-3">Question content :</div>
              <div class="col-md-9">
              <textarea class="form-control" name="blog[body]" rows="5" placeholder="Write question here" required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Post</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  <% end %>

app/views/admin/about.html.erb
 <% provide(:about, "active")%>
 <% provide(:title, "About")%>
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    	<!-- Indicators -->
    	<ol class="carousel-indicators">
    		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    		<li data-target="#myCarousel" data-slide-to="1"></li>
    		<li data-target="#myCarousel" data-slide-to="2"></li>
    	</ol>
    	<div class="carousel-inner" role="listbox">
    		<div class="item active">
    			<img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
    			<div class="container">
    				<div class="carousel-caption">
    					<h1>Example headline.</h1>
    					<p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
    					<p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
    				</div>
    			</div>
    		</div>
    		<div class="item">
    			<img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
    			<div class="container">
    				<div class="carousel-caption">
    					<h1>Another example headline.</h1>
    					<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
    					<p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
    				</div>
    			</div>
    		</div>
    		<div class="item">
    			<img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
    			<div class="container">
    				<div class="carousel-caption">
    					<h1>One more for good measure.</h1>
    					<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
    					<p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
    				</div>
    			</div>
    		</div>
    	</div>
    	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    		<span class="sr-only">Previous</span>
    	</a>
    	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    		<span class="sr-only">Next</span>
    	</a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

    	<!-- Three columns of text below the carousel -->
    	<div class="row">
    		<div class="col-lg-4">
    			<img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
    			<h2>Heading</h2>
    			<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
    			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    		</div><!-- /.col-lg-4 -->
    		<div class="col-lg-4">
    			<img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
    			<h2>Heading</h2>
    			<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
    			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    		</div><!-- /.col-lg-4 -->
    		<div class="col-lg-4">
    			<img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
    			<h2>Heading</h2>
    			<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    		</div><!-- /.col-lg-4 -->
    	</div><!-- /.row -->


    	<!-- START THE FEATURETTES -->

    	<hr class="featurette-divider">

    	<div class="row featurette">
    		<div class="col-md-7">
    			<h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
    			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    		</div>
    		<div class="col-md-5">
    			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
    		</div>
    	</div>

    	<hr class="featurette-divider">

    	<div class="row featurette">
    		<div class="col-md-7 col-md-push-5">
    			<h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
    			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    		</div>
    		<div class="col-md-5 col-md-pull-7">
    			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
    		</div>
    	</div>

    	<hr class="featurette-divider">

    	<div class="row featurette">
    		<div class="col-md-7">
    			<h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
    			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    		</div>
    		<div class="col-md-5">
    			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
    		</div>
    	</div>

    	<hr class="featurette-divider">

    	<!-- /END THE FEATURETTES -->


    	<!-- FOOTER -->
    	<footer>
    		<p class="pull-right"><a href="#">Back to top</a></p>
    		<p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    	</footer>

    </div><!-- /.container -->

app/views/admin/blog.html.erb
<% provide(:blog, "active")%>
<% provide(:title, "blog")%>
  <div class="container navbar navbar-default" style="width:100%; padding-top:0px; padding-bottom:10px;">
    <div class="blog-header">
      <h1 class="blog-title">The Bootstrap Blog</h1>
      <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      
      <button class="btn btn-success btn-lg pull-right" data-toggle="modal" data-target="#gridSystemModal"> Ask</button> 
    </div>
  </div>
  
  <div id="gridSystemModal" class="modal fade"  role="dialog" data-backdrop="false" aria-labelledby="gridSystemModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="gridSystemModalLabel">New a question</h4>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">
               <form role="form" class="form-horizontal" action="/questions" method="post"> 
                  <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                      <input type="email" id="email" name="email" class="form-control" placeHolder="Email" required/>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">Question</label>
                    <div class="col-sm-10">
                      <textarea class="form-control" rows="5" id="body" name="body" placeHolder="Question" required></textarea> 
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Post</button>
                  </div>
                </form>
            </div>
          </div>
          
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
   </div>
<div class="container">
  <div class="row">

    <div class="col-sm-8 blog-main">
      <% @blog.each do |row|%>
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img src="<%= row.gravatar%>" alt="" class="media-object">
            </a>
          </div><!--  media left -->
          <div class="media-body"> 
             <h4 class="media-heading"> <%=row.email%> asked:</h4>
             <div><%=time_ago_in_words row.created_at%>ago</div>
             <%= row.body%>
          </div>
        </div>  
        <% end %>
        
    </div>
  </div><!-- /.row -->
  </div><!-- /.container -->

app/views/admin/home.html.erb
<% provide(:home, "active")%>
<% provide(:title, "Home")%>
 <!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron header-action">   
    <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#gridSystemModal"><%= t('home.question') %></button>  
</div><%=I18n.locale %>
<div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= bootstrap_class_for(type) %> alert-dismissable fade in">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= message %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
        <% @blog.each do |b|%>
          <div class="media">
            <div class="media-left">
              <a href="javascript:void(0)">
                  <img class="media-object" src="<%= b.gravatar %>"></img>
              </a>
            </div>
            <div class="madia-body">
              <h4 class="media-heading"><%= b.email %> Asked:</h4>
              <div>
                <span><%= time_ago_in_words b.created_at%> ago</span>
              </div>
              <div>
                <label><%= b.body %></label>
              </div>     
              <div>
                <a href="<%= admin_path(b) %>" class="btn btn-success">View detail</a> 
              </div>         
            </div>
          </div>
          <% end %>
          <% if @blog.empty?%>
            <div class="alert alert-info"> Nothing here yet, be the first to ask</div>
          <% end%>         
        </div>
      </div>
    </div>

    <%= render 'new_blog_form'%>
      <hr>

      <footer class="screen-center">
        <p>&copy; Company 2014</p>
      </footer>
</div> <!-- /container -->

app/views/admin/show.html.erb
<% provide(:home, "active")%>
<% provide(:title, "Home")%> 
<div class="jumbotron header-action">  
    
</div>
<div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= bootstrap_class_for(type) %> alert-dismissable fade in">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= message %>
        </div>
      <% end %>
  	<div class="row">
	    <div class="col-md-12">
	    
	      	<div class="media">
		        <div class="media-left">
		          <a href="javascript:void(0)">
		              <img class="media-object" src="<%= @blog.gravatar %>"></img>
		          </a>
		        </div>
		        <div class="madia-body">
		          <h4 class="media-heading"><%= @blog.email %> Asked:</h4>
		          <div>
		            <span><%= time_ago_in_words @blog.created_at%> ago</span>
		          </div>
		          <div>
		            <label><%= @blog.body %></label>
		          </div>  
		        </div>        
	        </div>
        </div> 
	       <button type="button" class="btn btn-info btn-answer" data-toggle="modal" data-target="#answerModal">Answer</button>  
    </div> 
    
    <div class="row content-answer">

	    <div class="col-md-1"></div>
    	<div class="col-md-11"> 
		    <% @answer.each do |ans|%>
		    	<div class="media">
			        <div class="media-left">
			          <a href="javascript:void(0)">
			              <img class="media-object" src="<%= ans.gravatar %>"></img>
			          </a>
			        </div>
			        <div class="madia-body">
			          <h4 class="media-heading"><%= ans.email %> Answer:</h4>
			          <div>
			            <span><%= time_ago_in_words ans.created_at%> ago</span>
			          </div>
			          <div>
			            <label><%= ans.body %></label>
			          </div>          
			        </div>
			      </div> 
			    <% end %>
			    <% if @answer.empty?%>
		            <div class="alert alert-info"> Nothing here yet, be the first to answer</div>
		          <% end%>   
		      </div>		    
	    </div>	 
  	</div>
  <%= render 'new_answer_form'%>
      <hr>
      <footer class="screen-center">
        <p >&copy; Company 2014</p>
      </footer>
</div> <!-- /container -->

app/views/blogs/blog.html.erb
<% provide(:blog, "active")%>
<% provide(:title, "blog")%>
 <div class="container">

   <div class="blog-header">
    <h1 class="blog-title">The Bootstrap Blog</h1>
    <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
  </div>

  <div class="row">

    <div class="col-sm-8 blog-main">

     <div class="blog-post">
      <h2 class="blog-post-title">Sample blog post</h2>
      <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>

      <p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
      <hr>
      <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
      <blockquote>
       <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
     </blockquote>
     <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
     <h2>Heading</h2>
     <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
     <h3>Sub-heading</h3>
     <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
     <pre><code>Example code block</code></pre>
     <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
     <h3>Sub-heading</h3>
     <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
     <ul>
       <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
       <li>Donec id elit non mi porta gravida at eget metus.</li>
       <li>Nulla vitae elit libero, a pharetra augue.</li>
     </ul>
     <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
     <ol>
       <li>Vestibulum id ligula porta felis euismod semper.</li>
       <li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>
       <li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>
     </ol>
     <p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
   </div><!-- /.blog-post -->

   <div class="blog-post">
    <h2 class="blog-post-title">Another blog post</h2>
    <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

    <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
    <blockquote>
     <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
   </blockquote>
   <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
   <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
 </div><!-- /.blog-post -->

 <div class="blog-post">
  <h2 class="blog-post-title">New feature</h2>
  <p class="blog-post-meta">December 14, 2013 by <a href="#">Chris</a></p>

  <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  <ul>
   <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
   <li>Donec id elit non mi porta gravida at eget metus.</li>
   <li>Nulla vitae elit libero, a pharetra augue.</li>
 </ul>
 <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
 <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
</div><!-- /.blog-post -->

<nav>
  <ul class="pager">
   <li><a href="#">Previous</a></li>
   <li><a href="#">Next</a></li>
 </ul>
</nav>

</div><!-- /.blog-main -->

<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
 <div class="sidebar-module sidebar-module-inset">
  <h4>About</h4>
  <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
</div>
<div class="sidebar-module">
  <h4>Archives</h4>
  <ol class="list-unstyled">
   <li><a href="#">March 2014</a></li>
   <li><a href="#">February 2014</a></li>
   <li><a href="#">January 2014</a></li>
   <li><a href="#">December 2013</a></li>
   <li><a href="#">November 2013</a></li>
   <li><a href="#">October 2013</a></li>
   <li><a href="#">September 2013</a></li>
   <li><a href="#">August 2013</a></li>
   <li><a href="#">July 2013</a></li>
   <li><a href="#">June 2013</a></li>
   <li><a href="#">May 2013</a></li>
   <li><a href="#">April 2013</a></li>
 </ol>
</div>
<div class="sidebar-module">
  <h4>Elsewhere</h4>
  <ol class="list-unstyled">
   <li><a href="#">GitHub</a></li>
   <li><a href="#">Twitter</a></li>
   <li><a href="#">Facebook</a></li>
 </ol>
</div>
</div><!-- /.blog-sidebar -->

</div><!-- /.row -->

    </div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title)%></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body> 
	<%=render 'shared/navigation'%>
	<div class="main-page-content">
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <div class="language">
        <button type="button" class="btn btn-info">Tieng viet</button>
        <button type="button" class="btn btn-info">Tieng anh</button>
        <button type="button" class="btn btn-info">Tieng nhat</button> 
      </div>
      <a class="navbar-brand" href="javascript:void(0)">This is basic page</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= yield(:home)%>"><%= link_to "Home", root_path%></li>
        <li class="<%= yield(:about)%>"><%= link_to "About", about_path%></li>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</div><!-- /.container-fluid -->
</nav>